### ISSUE TITLE
Error - 'virtualenv' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by vands2013** [softwarepyrate/LPC_install#1]
While assisting John with the install, after the bat executed “pip install virtualenv” and tried to do “virtualenv seven --python=python3.9.13 “ then received the error - “'virtualenv' is not recognized as an internal or external command, operable program or batch file.”
Then we used the full command - “python -m virtualenv seven --python=python3.9.13” to make it work.
Cheers. 

Regards
Chen

**Comment by softwarepyrate** [comment]
Nice, thanks mate, will look now and incorporate

**Comment by softwarepyrate** [comment]
Issues resolved, batch file updated
